# ----------------------------
# Etapa 1: Build
# ----------------------------
    FROM node:18-alpine AS builder

    # Instala librerías básicas (compatibilidad, compilación ligera)
    RUN apk add --no-cache libc6-compat
    
    WORKDIR /app
    
    # Copiamos solo los manifests para aprovechar caché de dependencias
    COPY package*.json ./
    
    # Instalamos TODAS las dependencias (incluye devDeps)
    RUN npm ci
    
    # Copiamos el resto del código fuente
    COPY . .
    
    # Compilamos NestJS -> dist/
    RUN npm run build
    
    
    # ----------------------------
    # Etapa 2: Runtime
    # ----------------------------
    FROM node:18-alpine AS runner
    
    # Seguridad básica
    ENV NODE_ENV=production
    
    WORKDIR /app
    
    # Instala solo dependencias de producción
    COPY package*.json ./
    RUN npm ci --omit=dev
    
    # Copia la carpeta dist desde la etapa builder
    COPY --from=builder /app/dist ./dist
    
    # (Opcional) Copia otras carpetas necesarias (por ejemplo, mails, assets, vistas, etc.)
    # COPY --from=builder /app/public ./public
    
    # Exponemos el puerto estándar de Nest
    EXPOSE 3000
    
    # Usuario no-root para seguridad
    USER node
    
    # Comando de arranque
    CMD ["node", "dist/main.js"]